"""create comment_router table

Revision ID: 309c6e68162f
Revises: f379701cb55f
Create Date: 2026-07-26 10:04:56.048603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '309c6e68162f'
down_revision: Union[str, Sequence[str], None] = 'f379701cb55f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
                    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False,
                              comment='ID'),
                    sa.Column('text', sa.Text(), nullable=False, comment='餐廳評論'),
                    sa.Column('restaurant_id', sa.UUID(), nullable=False, comment='餐廳 ID'),
                    sa.Column('user_id', sa.UUID(), nullable=False, comment='使用者 ID'),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False,
                              comment='建立時間'),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False,
                              comment='修改時間'),

                    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.restaurant.id'], onupdate='CASCADE',
                                            ondelete='SET NULL'),
                    sa.ForeignKeyConstraint(['user_id'], ['restaurant.user.id'], onupdate='CASCADE',
                                            ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id'),
                    schema='restaurant'
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment', schema='restaurant')
    # ### end Alembic commands ###
