"""comment table user_id restaurant_id nullable

Revision ID: 34c949168dc6
Revises: e0dd0ac09378
Create Date: 2026-09-26 16:44:01.946821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34c949168dc6'
down_revision: Union[str, Sequence[str], None] = 'e0dd0ac09378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'restaurant_id',
               existing_type=sa.UUID(),
               nullable=True,
               existing_comment='餐廳 ID',
               schema='restaurant')
    op.alter_column('comment', 'user_id',
               existing_type=sa.UUID(),
               nullable=True,
               existing_comment='使用者 ID',
               schema='restaurant')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'user_id',
               existing_type=sa.UUID(),
               nullable=False,
               existing_comment='使用者 ID',
               schema='restaurant')
    op.alter_column('comment', 'restaurant_id',
               existing_type=sa.UUID(),
               nullable=False,
               existing_comment='餐廳 ID',
               schema='restaurant')
    # ### end Alembic commands ###
