"""update restaurant tel column

Revision ID: 4ae0b97e7cc2
Revises: 4b4ffc5eb973
Create Date: 2026-06-04 17:40:45.207045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ae0b97e7cc2'
down_revision: Union[str, Sequence[str], None] = '4b4ffc5eb973'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurant', 'tel',
               existing_type=sa.VARCHAR(length=128),
               nullable=True,
               existing_comment='餐廳電話',
               schema='restaurant')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurant', 'tel',
               existing_type=sa.VARCHAR(length=128),
               nullable=False,
               existing_comment='餐廳電話',
               schema='restaurant')
    # ### end Alembic commands ###
