"""update restaurant table

Revision ID: 4b4ffc5eb973
Revises: 4c062c351654
Create Date: 2026-06-01 18:07:23.750639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4b4ffc5eb973'
down_revision: Union[str, Sequence[str], None] = '4c062c351654'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurant', 'openingHours',
                    existing_type=sa.VARCHAR(length=32),
                    type_=sa.Integer(),
                    comment='營業時長',
                    existing_comment='餐廳電話',
                    existing_nullable=False,
                    schema='restaurant',
                    postgresql_using='"openingHours"::integer'
                    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurant', 'openingHours',
                    existing_type=sa.Integer(),
                    type_=sa.VARCHAR(length=32),
                    comment='餐廳電話',
                    existing_comment='營業時長',
                    existing_nullable=False,
                    schema='restaurant')
    # ### end Alembic commands ###
