"""create restaurant table

Revision ID: 4c062c351654
Revises: 4ec1421a6d1d
Create Date: 2026-05-27 22:38:52.400375

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4c062c351654'
down_revision: Union[str, Sequence[str], None] = '4ec1421a6d1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant',
                    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False,
                              comment='ID'),
                    sa.Column('name', sa.String(length=128), nullable=False, comment='餐廳名稱'),
                    sa.Column('tel', sa.String(length=128), nullable=False, comment='餐廳電話'),
                    sa.Column('openingHours', sa.String(length=32), nullable=False, comment='餐廳電話'),
                    sa.Column('address', sa.String(length=256), nullable=False, comment='餐廳地址'),
                    sa.Column('description', sa.Text(), nullable=True, comment='備註'),
                    sa.PrimaryKeyConstraint('id'),
                    schema='restaurant'
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restaurant', schema='restaurant')
    # ### end Alembic commands ###
