"""update user table

Revision ID: 4ec1421a6d1d
Revises: 761d6b8e5b26
Create Date: 2026-05-26 17:28:17.732571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ec1421a6d1d'
down_revision: Union[str, Sequence[str], None] = '761d6b8e5b26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否為管理員'), schema='restaurant')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin', schema='restaurant')
    # ### end Alembic commands ###
