"""create user table

Revision ID: 761d6b8e5b26
Revises: 
Create Date: 2026-05-23 12:22:18.326466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '761d6b8e5b26'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False,
                              comment='ID'),
                    sa.Column('name', sa.String(length=128), nullable=False, comment='使用者名稱'),
                    sa.Column('email', sa.String(length=256), nullable=False, comment='email'),
                    sa.Column('password', sa.String(length=128), nullable=False, comment='使用者密碼'),

                    sa.PrimaryKeyConstraint('id'),
                    schema='restaurant'
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user', schema='restaurant')
    # ### end Alembic commands ###
