"""create_menu_item_table

Revision ID: ab16b83f6d9e
Revises: dee36983e9fa
Create Date: 2026-08-27 10:22:39.708401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'ab16b83f6d9e'
down_revision: Union[str, Sequence[str], None] = 'dee36983e9fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_item',
                    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False,
                              comment='ID'),
                    sa.Column('restaurant_id', sa.UUID(), nullable=False, comment='餐廳 ID'),
                    sa.Column('name', sa.String(length=128), nullable=False, comment='餐點名稱'),
                    sa.Column('price', sa.Integer(), nullable=False, comment='價格（新台幣，整數）'),
                    sa.Column('section', sa.String(length=64), server_default=sa.text("'未分類'"), nullable=False,
                              comment='分區（例：前菜／主餐／飲料）'),
                    sa.Column('description', sa.Text(), nullable=True, comment='餐點描述'),
                    sa.Column('image', sa.String(length=256), nullable=True, comment='圖片連結'),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False,
                              comment='建立時間'),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False,
                              comment='更新時間'),
                    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.restaurant.id'], onupdate='CASCADE',
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    schema='restaurant'
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_item', schema='restaurant')
    # ### end Alembic commands ###
