"""add_created_at_and_updated_at_to_restaurant

Revision ID: be167697d848
Revises: 309c6e68162f
Create Date: 2026-08-06 19:54:52.153271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'be167697d848'
down_revision: Union[str, Sequence[str], None] = '309c6e68162f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 第一步 : 先將允許欄位為 True
    op.add_column('restaurant',
                  sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True,
                            comment='建立時間'), schema='restaurant')
    op.add_column('restaurant',
                  sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True,
                            comment='更新時間'), schema='restaurant')

    # 第二步 : 將既有資料的 NULL 欄位補上時間值（以當下時間或固定時間填入）
    op.execute('UPDATE "restaurant"."restaurant" SET created_at = NOW() WHERE created_at IS NULL')
    op.execute('UPDATE "restaurant"."restaurant" SET updated_at = NOW() WHERE updated_at IS NULL')

    # 第三步 : 修改欄位屬性為 NOT NULL (nullable=False)
    op.alter_column('restaurant', 'created_at', nullable=False, schema='restaurant')
    op.alter_column('restaurant', 'updated_at', nullable=False, schema='restaurant')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant', 'updated_at', schema='restaurant')
    op.drop_column('restaurant', 'created_at', schema='restaurant')
    # ### end Alembic commands ###
