"""add section_order to menu_item

Revision ID: bfb6bd980248
Revises: ab16b83f6d9e
Create Date: 2026-08-30 17:22:11.017778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfb6bd980248'
down_revision: Union[str, Sequence[str], None] = 'ab16b83f6d9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_item', sa.Column('section_order', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='分區排序（數字越小越前面，預設 0）'), schema='restaurant')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_item', 'section_order', schema='restaurant')
    # ### end Alembic commands ###
