"""create_cart_table

Revision ID: c7695bcc8418
Revises: bfb6bd980248
Create Date: 2026-09-04 14:56:07.068234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c7695bcc8418'
down_revision: Union[str, Sequence[str], None] = 'bfb6bd980248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
                    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False,
                              comment='ID'),
                    sa.Column('user_id', sa.UUID(), nullable=False, comment='使用者 ID'),
                    sa.Column('menu_item_id', sa.UUID(), nullable=False, comment='餐點 ID'),
                    sa.Column('quantity', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='數量'),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False,
                              comment='建立時間'),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False,
                              comment='更新時間'),
                    sa.ForeignKeyConstraint(['user_id'], ['restaurant.user.id'], onupdate='CASCADE',
                                            ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['menu_item_id'], ['restaurant.menu_item.id'], onupdate='CASCADE',
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    schema='restaurant'
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart', schema='restaurant')
    # ### end Alembic commands ###
