"""使用者資料表新增image欄位

Revision ID: dee36983e9fa
Revises: be167697d848
Create Date: 2026-08-16 17:59:27.675750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dee36983e9fa'
down_revision: Union[str, Sequence[str], None] = 'be167697d848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image', sa.String(length=256), nullable=True, comment='圖片連結'), schema='restaurant')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'image', schema='restaurant')
    # ### end Alembic commands ###
