"""create_order_table

Revision ID: e0dd0ac09378
Revises: c7695bcc8418
Create Date: 2026-09-24 14:30:05.122154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0dd0ac09378'
down_revision: Union[str, Sequence[str], None] = 'c7695bcc8418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='使用者 ID'),
    sa.Column('restaurant_id', sa.UUID(), nullable=True, comment='餐廳 ID'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False, comment='訂單狀態：pending/paid/failed/cancelled'),
    sa.Column('total_amount', sa.Integer(), nullable=False, comment='訂單總金額（新台幣，整數）'),
    sa.Column('merchant_trade_no', sa.String(length=20), nullable=False, comment='綠界特店交易編號（MerchantTradeNo）'),
    sa.Column('ecpay_trade_no', sa.String(length=30), nullable=True, comment='綠界交易編號（TradeNo）'),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True, comment='綠界回傳的付款時間'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新時間'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='ID'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.restaurant.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['restaurant.user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_trade_no'),
    schema='restaurant'
    )
    op.create_table('order_item',
    sa.Column('order_id', sa.UUID(), nullable=False, comment='訂單 ID'),
    sa.Column('menu_item_id', sa.UUID(), nullable=True, comment='餐點 ID'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='餐點名稱（結帳當下快照）'),
    sa.Column('unit_price', sa.Integer(), nullable=False, comment='單價（結帳當下快照）'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='數量'),
    sa.Column('subtotal', sa.Integer(), nullable=False, comment='小計'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='ID'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['restaurant.menu_item.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['restaurant.order.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='restaurant'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_item', schema='restaurant')
    op.drop_table('order', schema='restaurant')
    # ### end Alembic commands ###
