"""add restaurant image column

Revision ID: e6e77ede5822
Revises: 4ae0b97e7cc2
Create Date: 2026-06-08 11:27:23.991618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'e6e77ede5822'
down_revision: Union[str, Sequence[str], None] = '4ae0b97e7cc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('image', sa.String(length=256), nullable=True, comment='圖片連結'),
                  schema='restaurant')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant', 'image', schema='restaurant')
    # ### end Alembic commands ###
