"""create_category_table

Revision ID: f379701cb55f
Revises: e6e77ede5822
Create Date: 2026-06-27 11:43:54.579764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f379701cb55f'
down_revision: Union[str, Sequence[str], None] = 'e6e77ede5822'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
                    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False,
                              comment='ID'),
                    sa.Column('name', sa.String(length=128), nullable=False, comment='分類名稱'),
                    sa.PrimaryKeyConstraint('id'),
                    schema='restaurant'
                    )
    op.add_column('restaurant', sa.Column('category_id', sa.UUID(), nullable=True, comment='分類名稱'),
                  schema='restaurant')
    op.create_foreign_key('restaurant_category_id_fkey', 'restaurant', 'category', ['category_id'], ['id'],
                          source_schema='restaurant', referent_schema='restaurant', onupdate='CASCADE',
                          ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('restaurant_category_id_fkey', 'restaurant', schema='restaurant', type_='foreignkey')
    op.drop_column('restaurant', 'category_id', schema='restaurant')
    op.drop_table('category', schema='restaurant')
    # ### end Alembic commands ###
